config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    chmod: '644'
  d_lua:
    src: config/nvim/lua
    dst: ~/.config/nvim/lua
    chmod: '755'
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
    chmod: '644'
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
    chmod: '644'
profiles:
  joshua-x360:
    dotfiles:
    - f_zshrc
    - d_lua
    - f_init.lua
    - f_tmux.conf
